force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>Stores the Team Details.</description>
    <label>Team</label>
    <nameField>
        <displayFormat>Team-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/Fields/TeamName__c.field-meta.xml
<CustomField>
    <fullName>TeamName__c</fullName>
    <description>Name of the team.</description>
    <label>Team Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TeamMember__c/TeamMember__c.object-meta.xml
<CustomObject>
    <description>Stores the Team Member Details for a team.</description>
    <label>Team Member</label>
    <nameField>
        <displayFormat>TeamMember-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TeamMember__c/Fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <description>Used to store the skills of the particular team member.</description>
    <label>Skills</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/TeamMember__c/Fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <description>Stores parent Team.</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Team Member Fields</relationshipLabel>
    <relationshipName>TeamMemberFields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TeamMember__c/Fields/TeamMemberName__c.field-meta.xml
<CustomField>
    <fullName>TeamMemberName__c</fullName>
    <description>Name of the team member.</description>
    <label>Team Member Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TeamController.cls
public with sharing class TeamController {

    @AuraEnabled
    public static boolean addTeamMember(String memberName, String skills , id team){
        try{
            TeamMember__c teamMember= new TeamMember__c(TeamMemberName__c=memberName,Skills__c=skills , Team__c = team);
            insert teamMember;
            return true;
        }
        catch(Exception e){
            throw e;
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Team__c> getTeamList(){
        List<Team__c> teamList= [Select id,TeamName__c from Team__c];
        return teamList;
    }

    @AuraEnabled
    public static List<TeamMember__c> getTeamMemberList(){
        List<TeamMember__c> teamMemberList= [Select id,	TeamMemberName__c,Team__r.TeamName__c ,Skills__c from TeamMember__c];
        System.debug(teamMemberList);
        return teamMemberList;
    }

}